version: '3.9'

services:
  app:
    build:
      context: .
    container_name: app_dis
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./app:/app

  nginx:
    image: nginx:alpine
    container_name: nginx_dis
    ports:
      - 443:433
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs
      - ./app:/app
    depends_on:
      - app

  db:
    image: mongo
    container_name: db_dis
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mongo-data:/data/db

  mongo_express:
    image: mongo-express
    container_name: db_dis_express
    restart: always
    env_file:
      - .env
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_URL: ${DB_CONN}://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}
      ME_CONFIG_BASICAUTH: false
    volumes:
      - mongo-express-data:/data/db

volumes:
    mongo-data:
    mongo-express-data: