version: '3.9'

services:
  app:
    build:
      context: .
    container_name: app_dis
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt:ro
    restart: always
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  db:
    image: mongo
    container_name: db_dis
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mongo-data:/data/db

  mongo_express:
    image: mongo-express
    container_name: db_dis_express
    restart: always
    env_file:
      - .env
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${DB_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${DB_PASS}"
      ME_CONFIG_MONGODB_URL: "${DB_CONN}://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}"
    volumes:
      - mongo-express-data:/data/db

volumes:
    mongo-data:
    mongo-express-data: