name: Deployment Find Me

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_PRODUCTION }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_PRODUCTION }} <<EOF
            if [ ! -d "/home/${{ secrets.SSH_USER }}/dis_service" ]; then
              git clone git@github.com:fakhruddinarif/dis_service.git /home/${{ secrets.SSH_USER }}/dis_service
            fi
            cd /home/${{ secrets.SSH_USER }}/dis_service
            git pull
            docker-compose down
            docker-compose up --build -d
          EOF